### PR TITLE
Remove Linux font fixes

### PR DESCRIPTION
**Pull request by Rorriis**
As far as I can tell these changes haven't been necessary since the 64-bit update

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Can you confirm that reverting this won't bring back this issue? https://github.com/CriticalFlaw/TF2HUD-Fixes/pull/227

**Comment by CriticalFlaw** [comment]
@Rorriis see comment above

**Comment by Rorriis** [comment]
Checking now it seems the ammo seems broken, but the damage numbers fine. Apparently this is related to the desktop environment of the distro. Can't say what DEs are fine, but can tell that Cinnamon and Plasma 6 have the ammo bug

**Comment by CriticalFlaw** [comment]
Ah ok, then yeah lets keep things as-is for now. Thank you for checking

**Pull request closed without merging**
