### PR TITLE
Updated sizes of VGUI fonts

### PR DESCRIPTION
**Pull request by Kruphixx**
As per #286. You haven't specified if I should update the server browser font as well @CriticalFlaw so it's just this for now.

Before:
364529437-eff80df9-435a-4eb5-b469-b83e8b8433d0

After:
Screenshot 2024-09-06 114302

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Thanks. I took a look and think we'll probably need to scale more of that source window because it makes other elements look even smaller. Is there an existing mod we can reference?

**Comment by Kruphixx** [comment]
> Thanks. I took a look and think we'll probably need to scale more of that source window because it makes other elements look even smaller. Is there an existing mod we can reference?

I couldn't really find any mods that modify the font sizes specifically so a lot of stuff would have to be adjusted and tested manually. Shouldn't take very long, though

**Comment by Kruphixx** [comment]
Okay I updated fonts for all other VGUI panels to be bigger. I adjusted following fonts to increase their sizes:

- Default: 16 --> 17
- Default Small: 12 --> 14
- Default Bold: 16 --> 17

I also updated some of the fonts (such as the ones above, and console text) to add antialiasing to them since they looked very pixelated after increasing the size. I think the final result is very nice.

sourcescheme

**Comment by CriticalFlaw** [comment]
To be honest, I'm not seeing too much of a difference. I think you'll also need to add the `sourcescheme.res` file and modify that really increase the size of the console and browser. For sake of a test, I copied it and sourceschemebase.res from Open Fortress

**Comment by Kruphixx** [comment]
I guess the difference will be more noticeable side-by-side. I don't think sourcescheme.res is needed, everything needed is in sourceschemebase.

Before:


After:

**Comment by CriticalFlaw** [comment]
Oh yeah now I see it. That actually looks quite good. Thank you again for adding this in.

**Pull request merged**
